- Model/Sorghum/Biomass.cpp
- Model/Sorghum/Grain.cpp
- Model/Sorghum/Plant.cpp
- Model/Sorghum/Plant.h
- Model/Sorghum/PlantActions.cpp
- Model/Sorghum/Roots.cpp
Resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1734
> Use null-typed event callbacks unless structure is passed

- Model/Build/BuildAll.bat
- Model/ReportDb/ReportDb.csproj
> Fix local compile with VS2017

- Model/Plant/Root/RootPart.cpp
Resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1724
> ensure root maintenance coefficient is initialised properly 

- Model/JobScheduler/CreateDiffZip/CreateDiffZip.cs
- Release/CreateInstall.bat
- Tests/SiloInput/SiloInput.SILO sample.sum
Working on #1747
This will work around the problem for the time being, but as soon as Inno Setup 7 is released, we will run into this problem again.
> Updated inno setup path.

- Model/ApsimUI/ApsimUISplash.Designer.cs
- Model/ApsimUI/ApsimUISplash.cs
Resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1745
> Added AI acknowledgement message to splash screen

- Model/DDRules/DDRules.vbproj
- Model/DDRules/DDRulesTypes/DDRulesTypes.vbproj
- Model/DDRules/DairyCows/DairyCows.vbproj
- Model/DDRules/EffluentIrrigator/EffluentIrrigator.vbproj
- Model/DDRules/EffluentPond/EffluentPond.vbproj
- Model/DDRules/FeedStore/FeedStore.vbproj
- Model/FarmSimGraze/FarmSimGraze.vbproj
- Model/MicroClimate/MicroClimate.vbproj
- Model/Root/Root.vbproj
- Model/SoilTemp2/SoilTemp2.vbproj
- Model/UrinePatch/UrinePatch.vbproj
Resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1655
> Workaround for mono vb zombies left running after compilation

- Model/Actions/ApsimUIActions.cs
- Model/Actions/SoilActions.cs
- Model/ApsimFile/Component.cs
- Model/Build/Bob.cs
- Model/Build/BobMain.cs
- Model/Build/BuildAll.xml
- Model/FTP/FTPClient.cs
- Model/JobScheduler/ApsimBuildsDB.cs
- Model/JobScheduler/CreateDiffZip/CreateDiffZip.cs
- Model/JobScheduler/CreatePatch/CreatePatch.cs
- Model/JobScheduler/CreateSummaryHtml/CreateSummaryHtml.cs
- Model/JobScheduler/IfCleanDoCommit/IfCleanDoCommit.cs
- Model/JobScheduler/UpdateFieldInDB/UpdateFieldInDB.cs
- Release/CreateInstall.bat
> Changed BuildAll.xml to use git clean rather than heavy-duty C# script.

- Model/Apsim/Apsim.cs
- Model/ApsimFile/RunCondorJob.cs
resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1753
> properly quote command arguments to Apsim.exe

- Model/RLink/Makefile.linux
resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1773
> Fix linux makefile for RDataTypes

- Apsim.xml
- Examples/Advanced/GriddedGrazedPaddock.apsim
- Examples/Wether Lucerne Supplement.apsim
- Model/Build/BuildAll.xml
- Release/ApsimSetup.iss
- Release/Exclusions.txt
- Release/UserInterfaceExcludes.iss
- Tests/Manager2/DateTest.apsim
- Tests/Manager2/Plant2Reference.apsim
- Tests/Manager2/Plant2_ComponentModel.apsim
- Tests/SoilNitrogen/CompareOldNew/SoilN-SoilNitrogen_ComparisonTests(ShortTerm).apsim
- Tests/SoilNitrogen/GriddedGrazedPaddockExample.apsim
- Tests/SoilNitrogen/SoilCNPatch/SoilNitrogen_CNPatch_BasicTests.apsim
- Tests/SoilNitrogen/SoilCNPatch/SoilNitrogen_CNPatch_VariabilityTests.apsim
- Tests/SoilNitrogen/SoilCNPatch/outputTests/SoilNitrogen_CNPatch_OutputsTests.apsim
- Tests/SoilNitrogen/SoilNitrogen.apsim
- UserInterface/Non-Validated.xml
- UserInterface/ToolBoxes/Non-Validated.xml
Resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1757
@hol430 - this will not produce a bootleg installer (aka 1757.bootleg.exe), which will probably upset jenkins...
> Move Bootleg to Non-Validated, remove bootleg installer

- Model/Sorghum/Grain.cpp
> Added guard clause to sorghum grain number calculation.

- Model/Sorghum/Biomass.cpp
- Model/Sorghum/Utilities.cpp
Recent changes to sorghum  https://github.com/APSIMInitiative/APSIMClassic/issues/1770 broke unix builds
> Unix paths for sorghum/dcaps #1790

- Model/Tests/xmlunit/xmlunit.csproj
Working on #1819 
Builds seem to be broken. Hope this will fix the problem.
> Update xmlunit to use .NET Framework 4.5

- Model/Build/BuildAll.xml
- Model/Build/VersionStamper.cs
- README.md
> Update BuildAll.xml to separate installer generation from regular jenkins runs

- Model/Maize/Phosphorus.cpp
- Model/MaizePioneer/Phosphorus.cpp
> Correct typo causing maize to not see P limitations.

- Model/Build/BuildAll.xml
- Model/Build/VersionStamper.cs
Should default to 0 if this env var does not exist(?).
Resolves #1853
> BuildAll.xml should pass revision number to version stamper

- Model/Build/VersionStamper.cs
> C#/VB assembly version should include revision number.

- Release/CreateInstall.bat
> Re-enable signing of installers

- Model/FortranInfrastructure/PublishEvents.f90
- Model/Maize/Biomass.cpp
- Model/Maize/Grain.cpp
- Model/Maize/Leaf.cpp
- Model/Maize/Nitrogen.cpp
- Model/Maize/Phenology.cpp
- Model/Maize/Phosphorus.cpp
- Model/Maize/Plant.cpp
- Model/Maize/PlantComponents.cpp
- Model/Maize/Rachis.cpp
- Model/Maize/Roots.cpp
- Model/Maize/Stem.cpp
- Model/Sorghum/Biomass.cpp
- Model/Sorghum/Leaf.cpp
- Model/Sorghum/LeafCulms.cpp
- Model/Sorghum/Phosphorus.cpp
Resolves #1729 
@jbrider this *may* be related to the occasional empty summary file you're seeing, but I still can't reproduce it so I'm not really sure.
> Ensure that maize's aboveGroundGreenBiomass is initialized properly.

- Model/SoilWat/SoilWat.for
resolves https://github.com/APSIMInitiative/APSIMClassic/issues/1914
> increase max_crops in soilwat

- Model/ApsimFile/RunCondorJob.cs
> Replacing the correct xml document in RunCondorJobs.cs

- Model/ApsimFile/RunCondorJob.cs
Resolves #2047 
@peter-devoil Do you approve this change? I am not sure if for a reason you turned the "overwrite" off.
> Bundle currently does not overwrite Plugin files.

- Model/Sugar/SugarMain.for
> Sugarcane N uptake was always zero

- Model/Sugar/Sugar.for
- Model/Sugar/SugarMain.for
> lodge_flag and rue need to be exposed in Sugarcane

- Model/JobScheduler/CreateDiffZip/CreateDiffZip.cs
- Model/JobScheduler/IfCleanDoCommit/RESTUtility.cs
> Added authorization header to web api call UpdateNumDiffs

- Model/Sugar/SugarMain.for
> Added 'residue_wt' to sugar module to calculate burnt material before harvest

- Model/CSUserInterface/ProfileUI.Designer.cs
> Widen Properties grid to allow space for possible vertical scrollbar.

- Release/ApsimSetup.iss
> Change to trigger build on Jenkins

- Release/ApsimSetup.iss
> Revert "Change to trigger build on Jenkins"
